### ISSUE TITLE
Missing const qualifiers for parameters...

### ISSUE THREAD

**Issue by eyalroz** [sadhbh-c0d3/examples#1]
In your C++ code, you occasionally pass by non-const reference, ,e.g. [here](https://github.com/sadhbh-c0d3/examples/blob/main/dispatch/p1_cpp_dispatch/s3_virtual.cpp#L24):
```
int total_area1(Shape &s1, Shape &s2)
```
which should be
```
int total_area1(Shape const &s1, Shape const &s2)
```
Also, if I've missed it - non-const pointers and non-const references, if you really need them, [can be helped by `__restrict__`](https://stackoverflow.com/q/12841279/1593077), which isn't officially in the language, but is widely supported.

**Comment by sadhbh-c0d3** [comment]
Hey, it's done on purpose. I wanted to see if I get virtual call, but as I have presented on video I believe optimiser has removed the need for virtual call. Of course you can invoke virtual methods via const reference too, but since it's const there are higher chances that optimiser will ditch it. The idea was to present what will happen if I use runtime polymorphism and compare it to static. Did you watch my video?

**Comment by eyalroz** [comment]
I realize that, but I thought you were aiming to show very idiomatic code, which is why I made the suggestion. It's not a big deal.
